apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: broker
spec:
  console:
    expose: true
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    storage:
      size: 1Gi
    extraMounts:
      secrets:
      - "newlog4j-logging-config"


