apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: west
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    authorization:
      type: simple
    listeners:
      - name: scramsha512
        port: 9093
        type: route
        tls: true
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}

