apiVersion: v1
kind: Pod
metadata:
  name: storage-check
  namespace: openshift-storage-operator
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: "/data"
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: san-test-pvc
