security.protocol=SSL
ssl.keystore.location=/tmp/ca-data/certs/myserver.p12
ssl.keystore.password=foobar
ssl.truststore.location=/tmp/ca-data/certs/truststore.p12
ssl.truststore.password=foobar
client.id=my-kafka-client
