node.id=2
log.dirs=/tmp/kraft-controller-logs-2
listeners=CONTROLLER://127.0.0.1:10092
advertised.listeners=CONTROLLER://127.0.0.1:10092

listener.security.protocol.map=CONTROLLER:SSL
controller.quorum.bootstrap.servers=127.0.0.1:10090,127.0.0.1:10091,127.0.0.1:10092
controller.listener.names=CONTROLLER

authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
super.users=User:myserver;User:admin

ssl.keystore.location=/tmp/ca-data/certs/myserver.p12
ssl.keystore.password=foobar
ssl.truststore.location=/tmp/ca-data/certs/truststore.p12
ssl.truststore.password=foobar
ssl.client.auth=required
ssl.principal.mapping.rules=RULE:^CN=(.*?),OU=.*$/$1/,DEFAULT

###### for kraft admin client (add-controller uses this file as --command-config)
security.protocol=SSL
######

process.roles=controller
num.network.threads=3
num.io.threads=8
socket.send.buffer.bytes=102400
socket.receive.buffer.bytes=102400
socket.request.max.bytes=104857600
num.partitions=1
num.recovery.threads.per.data.dir=1
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
log.retention.hours=168
log.segment.bytes=1073741824
log.retention.check.interval.ms=300000
