-- Debezium Oracle Test Database Initialization
-- Creates sample inventory tables with products, customers, and orders

-- Enable supplemental logging at database level (required for Debezium)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Create and populate products table
CREATE TABLE products (
  id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 101) NOT NULL PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  description VARCHAR2(512),
  weight FLOAT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
GRANT SELECT ON products to debezium;
ALTER TABLE products ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO products VALUES (NULL,'scooter','Small 2-wheel scooter',3.14,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'car battery','12V car battery',8.1,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'12-pack drill bits','12-pack of drill bits with sizes ranging from #40 to #3',0.8,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'hammer','12oz carpenter''s hammer',0.75,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'hammer','14oz carpenter''s hammer',0.875,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'hammer','16oz carpenter''s hammer',1.0,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'rocks','box of assorted rocks',5.3,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'jacket','water resistent black wind breaker',0.1,CURRENT_TIMESTAMP);
INSERT INTO products VALUES (NULL,'spare tire','24 inch spare tire',22.2,CURRENT_TIMESTAMP);
COMMIT;

-- Create and populate products inventory table
CREATE TABLE products_on_hand (
  product_id NUMBER(4) NOT NULL PRIMARY KEY,
  quantity NUMBER(4) NOT NULL,
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id)
);
GRANT SELECT ON products_on_hand to debezium;
ALTER TABLE products_on_hand ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO products_on_hand VALUES (101,3,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (102,8,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (103,18,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (104,4,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (105,5,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (106,0,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (107,44,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (108,2,CURRENT_TIMESTAMP);
INSERT INTO products_on_hand VALUES (109,5,CURRENT_TIMESTAMP);
COMMIT;

-- Create and populate customers table
CREATE TABLE customers (
  id NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1001) NOT NULL PRIMARY KEY,
  first_name VARCHAR2(255) NOT NULL,
  last_name VARCHAR2(255) NOT NULL,
  email VARCHAR2(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
GRANT SELECT ON customers to debezium;
ALTER TABLE customers ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO customers VALUES (NULL,'Sally','Thomas','sally.thomas@acme.com',CURRENT_TIMESTAMP);
INSERT INTO customers VALUES (NULL,'George','Bailey','gbailey@foobar.com',CURRENT_TIMESTAMP);
INSERT INTO customers VALUES (NULL,'Edward','Walker','ed@walker.com',CURRENT_TIMESTAMP);
INSERT INTO customers VALUES (NULL,'Anne','Kretchmar','annek@noanswer.org',CURRENT_TIMESTAMP);
COMMIT;

-- Create and populate orders table
CREATE TABLE orders (
  id NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10001) NOT NULL PRIMARY KEY,
  order_date DATE NOT NULL,
  purchaser NUMBER(4) NOT NULL,
  quantity NUMBER(4) NOT NULL,
  product_id NUMBER(4) NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING',
  FOREIGN KEY (purchaser) REFERENCES customers(id),
  FOREIGN KEY (product_id) REFERENCES products(id)
);
GRANT SELECT ON orders to debezium;
ALTER TABLE orders ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO orders VALUES (NULL, TO_DATE('16-JAN-2016','DD-MON-YYYY'), 1001, 1, 102, 'SHIPPED');
INSERT INTO orders VALUES (NULL, TO_DATE('17-JAN-2016','DD-MON-YYYY'), 1002, 2, 105, 'SHIPPED');
INSERT INTO orders VALUES (NULL, TO_DATE('19-FEB-2016','DD-MON-YYYY'), 1002, 2, 106, 'PENDING');
INSERT INTO orders VALUES (NULL, TO_DATE('21-FEB-2016','DD-MON-YYYY'), 1003, 1, 107, 'SHIPPED');
COMMIT;

-- Display summary
SELECT 'Database initialization complete!' as status FROM dual;
SELECT COUNT(*) as product_count FROM products;
SELECT COUNT(*) as customer_count FROM customers;
SELECT COUNT(*) as order_count FROM orders;
